routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use App\User;
use App\Gallery;
use App\Participant;
use App\News;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
// ['register' => false]
Route::get('/password/reset',function(){
    return redirect('/home');
});

Route::get('/',function(){
    return redirect('/home');
});
// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@landing')->name('landing');
Route::get('/sendgmail', 'HomeController@sendGmail');

Route::post('/registered','RegisterWorkshopController@store')->name('register_workshop');

Route::middleware('auth')->group(function(){
    Route::prefix('admin')->middleware('admin')->group(function(){

        Route::get('/',function(){

            $user = Auth::user();

            return view('admin.admin', compact('user'));
        })->name('admin');

        Route::resource('news','NewsController')->except([
            'show','destroy'
        ]);
        Route::get('news/recent-news', 'NewsController@recent')->name('news.recent');

        Route::resource('galleries', 'GalleryController')->except([
            'show','destroy'
        ]);

        Route::resource('participants', 'ParticipantController')->except([
            'show','destroy'
        ]);

        Route::resource('adminAccount', 'AdminAccountController')->except([
            'show','destroy'
        ]);

        Route::get('/news/{news}','NewsController@destroy')->name('news.destroy');
        Route::get('/account/{account}','AdminAccountController@destroy')->name('account.destroy');
        Route::resource('registered', 'RegisterWorkshopController')->except([
            'show','destroy','create','store','update'
        ]);

        Route::get('/news/{news}','NewsController@destroy')->name('news.destroy');
        Route::get('/registered/{registered}','RegisterWorkshopController@destroy')->name('registered.destroy');
        Route::put('/registered/bayar/{registered}','RegisterWorkshopController@update')->name('registered.pay');
        Route::put('/news/change-status/{status}','NewsController@changeStatus')->name('news.change');
        Route::get('admin/galleries/{gallery}','GalleryController@destroy')->name('galleries.destroy');
        Route::get('admin/participants/{participant}','ParticipantController@destroy')->name('participants.destroy');
    });
});

app/Participant.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Participant extends Model
{
    protected $fillable = [
        'title',
        'description',
        'picture',
    ];
}

app/Http/Controllers/ParticipantController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Carbon\Carbon;
use App\Participant;
use View;
use Illuminate\Support\Facades\Auth;

class ParticipantController extends Controller
{
    public function index(){

        $user = Auth::user();

        $participants = Participant::all();

        return view('admin.participants.index')->with(compact('participants','user'));
    }

    public function create(){

        $user = Auth::user();
        $participants = Participant::all();

        return View::make('admin.participants.add')
            ->with(compact('participants','user'));
    }

    public function store(Request $request){

        $gambar = $request->file('file');
        //dd($gambar);
        $namafile = Carbon::now()->timestamp. '_' . uniqid() . '.' . $gambar->getClientOriginalExtension();
        $gambar->move(public_path('upload/participants/'),$namafile);

        Participant::create([
            'title' => $request['title'],
            'description' => $request['description'],
            'picture' => $namafile
        ]);

        return redirect('admin/participants');

    }

    public function edit($id){

        $user = Auth::user();

        $participant  = Participant::where('id',$id)->first();


        return View::make('admin.participants.edit')
            ->with(compact('participant','user'));

    }

    public function update(Request $request, $id){

        $participant = Participant::find($id);
        //dd($request->all());
        if($participant->picture == $request['picture']){
            $fotoLama = $request['picture'];
        }else{
            $fotoLama = $participant->picture;
        }

        $foto = $request->file('file');

        //dd($foto);

        if(empty($foto)){
            $foto = $fotoLama;
            $namabaru = $foto;
        }else{
            $foto = $request->file('file');
            $namabaru = Carbon::now()->timestamp. '_' . uniqid() . '.' .$foto->getClientOriginalExtension();
            $foto->move(public_path('upload/participants/'),$namabaru);
            unlink(public_path('\upload\participants\\'.$fotoLama));
        }

        //dd($participant);

        Participant::where('id', $id)->update([
            'title' => $request['title'],
            'description' => $request['description'],
            'picture' => $namabaru
        ]);

        return redirect('admin/participants');

    }

    public function destroy($id){
        //dd($id);
        $participant = Participant::find($id);
        unlink(public_path('\upload\participants\\'.$participant->picture));
        $participant->delete();


        return redirect('/admin/participants');
    }

}

resources/views/admin/participants/add.blade.php
@extends('layouts.admin.app')
@section('title','Dashboard | Participants')
@section('content')

<div class="m-grid m-grid--hor m-grid--root m-page">
    <!-- BEGIN: Header -->


    <!-- begin::Body -->
    <div
      class="m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body"
    >

      <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title m-subheader__title--separator">Page</h3>
                    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                        <li class="m-nav__item m-nav__item--home">
                            <a href="#" class="m-nav__link m-nav__link--icon">
                                <i class="m-nav__link-icon la la-home"></i>
                            </a>
                        </li>
                        <li class="m-nav__separator">-</li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
                                <span class="m-nav__link-text">Page</span>
                            </a>
                        </li>
                        <li class="m-nav__separator">-</li>
                        <li class="m-nav__item">
                            <a href="" class="m-nav__link">
                                <span class="m-nav__link-text">Add Picture</span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- END: Subheader -->
        <div class="m-content">
			<div class="row">
                <div class="col-xl-12">
                    <!--Begin::Portlet-->
                    <div class="m-portlet m-portlet--head-lg">
                        <div class="m-portlet__body no-pedding">
                            <div class="m-portlet__head">
                                <div class="m-portlet__head-caption">
                                    <div class="m-portlet__head-title">
                                        <span class="m-portlet__head-icon">
                                            <i class="la la-table"></i>
                                        </span>
                                        <h3 class="m-portlet__head-text">
                                            Participants Add
                                        </h3>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <form action="{{ route('participants.store') }}" method="POST" enctype="multipart/form-data" class="m-form m-form--state m-form--label-align-left">
                            @csrf
                            <div class="m-portlet__body">
                                <div class="row">
                                    <div class="col-xl-12">
                                        <div class="m-form__section">
                                            <div class="form-group m-form__group row">

												<div class="col-lg-6 m-form__group-sub">
													<label class="form-control-label">
                                                        Title
                                                    </label>
													<input type="text" name="title" class="form-control m-input" placeholder="Enter text">
													<div class="form-control-feedback">
                                                        Sorry, that username's taken. Try another?
                                                    </div>
													<span class="m-form__help">
                                                        Please enter your text
                                                    </span>
                                                </div>
                                                <div class="col-lg-6 m-form__group-sub">
                                                    <label class="form-control-label">Gambar</label>
													<div class="input-group file-input">
														<input type="file" name="file" class="upload" multiple>
														<input class="form-control"  name="picture" placeholder="No File Selected" type="text">
														<span class="remove-file"><i class="la la-times-circle"></i></span>
														<div class="input-group-append">
															<button type="button" class="btn btn-primary file-name"><i class="la la-file"></i></button>
														</div>
													</div>
                                                </div>

                                            </div>
                                            <div class="form-group m-form__group row">
                                                <div class="col-lg-12 m-form__group-sub">
                                                    <label class="col-form-labe">
                                                        Description
                                                    </label>
                                                    <textarea class="summernote" name="description" id="m_summernote_1"></textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit">
                                <div class="m-form__actions m-form__actions--solid">
                                    <div class="row">
                                        <div class="col-xl-12 m--align-right">
                                            <button type="submit" class="btn btn-danger btn-sm m-btn--pill m-btn--air m-btn--wide">
                                                Submit
                                            </button>
                                            <a href="{{route('participants.index')}}" class="btn btn-secondary btn-sm m-btn--wide m-btn--pill m--margin-left-5">Cancel</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
			</div>
        </div>
    </div>
</div>
</div>

  <!-- end:: Page -->

  <!-- begin::Scroll Top -->
  <div id="m_scroll_top" class="m-scroll-top">
    <i class="la la-arrow-up"></i>
  </div>

  <!-- end::Scroll Top -->
@endsection

@section('admin-js')
  <script>
        $(document).ready(function() {

            $('.summernote').summernote({
                 height: 100,
            });

        } );
  </script>
@endsection

resources/views/admin/participants/edit.blade.php
@extends('layouts.admin.app')
@section('title','Dashboard | Participants')

@section('content')

<div class="m-grid m-grid--hor m-grid--root m-page">
    <!-- BEGIN: Header -->


    <!-- begin::Body -->
    <div
      class="m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body"
    >

      <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title m-subheader__title--separator">Participants</h3>
                    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                        <li class="m-nav__item m-nav__item--home">
                            <a href="{{ route('admin') }}" class="m-nav__link m-nav__link--icon">
                                <i class="m-nav__link-icon la la-home"></i>
                            </a>
                        </li>
                        <li class="m-nav__separator">-</li>
                        <li class="m-nav__item">
                            <a href="{{ route('participants.index') }}" class="m-nav__link ">
                                <span class="m-nav__link-text">Participants</span>
                            </a>
                        </li>
                        <li class="m-nav__separator">-</li>
                        <li class="m-nav__item">
                            <a href="{{ route('participants.edit', $participant->id) }}" class="m-nav__link ">
                                <span class="m-nav__link-text">Edit</span>
                            </a>
                        </li>
                        <li class="m-nav__separator">-</li>
                        <li class="m-nav__item">
                            <a href="javascript:;" class="m-nav__link ">
                                <span class="m-nav__link-text">
                                    {{$participant->id }}
                                </span>
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>

        <!-- END: Subheader -->
        <div class="m-content">
			<div class="row">
                <div class="col-xl-12">
                    <!--Begin::Portlet-->
                    <div class="m-portlet m-portlet--head-lg">
                        <div class="m-portlet__body no-pedding">
                            <div class="m-portlet__head">
                                <div class="m-portlet__head-caption">
                                    <div class="m-portlet__head-title">
                                        <span class="m-portlet__head-icon">
                                            <i class="la la-table"></i>
                                        </span>
                                        <h3 class="m-portlet__head-text">
                                            Participants Edit
                                        </h3>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <form action="{{ route('participants.update', $participant->id) }}" method="POST" enctype="multipart/form-data" class="m-form m-form--state m-form--label-align-left">
                            @csrf
                            @method('put')
                            <div class="m-portlet__body">
                                <div class="row">
                                    <div class="col-xl-12">
                                        <div class="m-form__section">
                                            <div class="form-group m-form__group row">

												<div class="col-lg-6 m-form__group-sub">
													<label class="form-control-label">
                                                        Title
                                                    </label>
													<input type="text" name="title" class="form-control m-input" value="{{ $participant->title }}">
													<div class="form-control-feedback">
                                                        Sorry, that username's taken. Try another?
                                                    </div>
													<span class="m-form__help">
                                                        Please enter your text
                                                    </span>
                                                </div>
                                                <div class="col-lg-6 m-form__group-sub">
                                                    <label class="form-control-label">Gambar</label>
													<div class="input-group file-input">
														<input type="file" name="file" class="upload" multiple>
														<input class="form-control"  name="picture" type="text" value="{{ $participant->picture }}">
														<span class="remove-file"><i class="la la-times-circle"></i></span>
														<div class="input-group-append">
															<button type="button" class="btn btn-primary file-name"><i class="la la-file"></i></button>
														</div>
													</div>
                                                </div>

                                            </div>
                                            <div class="form-group m-form__group row">
                                                <div class="col-lg-12 m-form__group-sub">
                                                    <label class="col-form-labe">
                                                        Description
                                                    </label>
                                                    <textarea class="summernote" name="description" id="m_summernote_1">{{ $participant->description }}</textarea>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="m-portlet__foot m-portlet__foot--fit">
                                <div class="m-form__actions m-form__actions--solid">
                                    <div class="row">
                                        <div class="col-xl-12 m--align-right">
                                            <button type="submit" class="btn btn-danger btn-sm m-btn--pill m-btn--air m-btn--wide">
                                                Update
                                            </button>
                                            <a href="{{route('participants.index')}}" class="btn btn-secondary btn-sm m-btn--wide m-btn--pill m--margin-left-5">Cancel</a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
			</div>
        </div>
    </div>
</div>
</div>

  <!-- end:: Page -->

  <!-- begin::Scroll Top -->
  <div id="m_scroll_top" class="m-scroll-top">
    <i class="la la-arrow-up"></i>
  </div>

  <!-- end::Scroll Top -->
@endsection

@section('admin-js')
  <script>
        $(document).ready(function() {


        } );
  </script>
@endsection

resources/views/admin/participants/index.blade.php
@extends('layouts.admin.app')
@section('title','Dashboard | Participant')

@section('content')

<div class="m-grid m-grid--hor m-grid--root m-page">
    <!-- BEGIN: Header -->


    <!-- begin::Body -->
    <div
      class="m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body"
    >

      <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title m-subheader__title--separator">Participants</h3>
                    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                        <li class="m-nav__item m-nav__item--home">
                            <a href="{{ route('admin') }}" class="m-nav__link m-nav__link--icon">
                                <i class="m-nav__link-icon la la-home"></i>
                            </a>
                        </li>
                        <li class="m-nav__separator">-</li>
                        <li class="m-nav__item">
                            <a href="{{ route('participants.index') }}" class="m-nav__link ">
                                <span class="m-nav__link-text">Participants</span>
                            </a>
                        </li>

                    </ul>
                </div>
            </div>
        </div>

        <!-- END: Subheader -->
        <div class="m-content">
			<div class="row">
                <div class="col-xl-12">
                    <!--Begin::Portlet-->
                    <div class="m-portlet m-portlet--head-lg">
                        <div class="m-portlet__body no-pedding">
                            <div class="m-portlet__head">
                                <div class="m-portlet__head-caption">
                                    <div class="m-portlet__head-title">
                                        <span class="m-portlet__head-icon">
                                            <i class="la la-table"></i>
                                        </span>
                                        <h3 class="m-portlet__head-text">
                                            Table Participants
                                        </h3>
                                    </div>
                                </div>
                                <div class="m-portlet__head-tools">
                                <ul class="m-portlet__nav">
                                    <li class="m-portlet__nav-item">
                                        <a href="{{ route('participants.create') }}" class="btn m-btn btn-brand btn-sm m-btn--icon m-btn--pill m-btn--air">
                                            <span>
                                                <i class="la la-plus"></i>
                                                <span>Add Item</span>
                                            </span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table class="table align-items-center table-flush" id="table-id">
                                <thead class="thead-light">
                                    <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Title</th>
                                    <th scope="col">Desctription</th>
                                    <th scope="col">Picture</th>
                                    <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach ($participants as $g)
                                    <tr>
                                        <th>{{ $g->id }}</th>
                                        <td>{{ $g->title }}</td>
                                        <td>{!! $g->description !!}</td>
                                        <td>
                                            <img src="{{asset('public/upload/participants/'.$g->picture)}}" width="100px" alt="foto">
                                        </td>
                                        <td>
                                            <div class="section__action">
												<div class="list__section__action">

													<a href="{{ route('participants.edit', $g->id) }}" data-toggle="kt-tooltip" data-placement="bottom" data-skin="dark" title="Edit" class="btn m-btn btn-success btn-sm m-btn--icon m-btn--air icon-only">
														<span>
															<i class="la la-pencil"></i>
														</span>
													</a>
													<a href="#" data-toggle="kt-tooltip" data-placement="bottom" data-skin="dark" title="Delete" data-id="{{ route('participants.destroy', $g->id) }}" class="btn m-btn btn-danger btn-sm  m-btn--icon m-btn--pill icon-only m_sweetalert_5">
                                                        <span>
															<i class="la la-trash"></i>
														</span>
													</a>
												</div>

											</div>
                                        </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
			</div>
        </div>
    </div>
</div>
</div>

  <!-- end:: Page -->

  <!-- begin::Scroll Top -->
  <div id="m_scroll_top" class="m-scroll-top">
    <i class="la la-arrow-up"></i>
  </div>

  <!-- end::Scroll Top -->
@endsection

@section('admin-js')
  <script>
        $(document).ready(function() {

            $(function () {
                $('[data-toggle="kt-tooltip"]').tooltip();
            })

            $('.btn-danger').on('click', function() {


            Swal.fire({
            title: 'Are you sure?',
            text: "You won't be able to revert this!",
            type: 'warning',
            showCancelButton: true,
            confirmButtonColor: 'red',
            cancelButtonColor: 'blue',
            confirmButtonText: 'Yes, delete it!',
            cancelButtonText: 'No, cancel'
            }).then((result) => {
                if (result.value) {

                    var data = $(this).data('id')
                    console.log(data)
                    window.location = data;

                }else{
                    Swal.fire(
                    'Cancelled!',
                    'Your file has been cancel.',
                    'error'
                    )
                }

            })
        })

        } );
  </script>
@endsection