routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use App\User;
use App\Gallery;
use App\Participant;
use App\News;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Auth::routes();
// ['register' => false]
Route::get('/password/reset',function(){
    return redirect('/home');
});

Route::get('/',function(){
    return redirect('/home');
});
// Route::get('/home', 'HomeController@index')->name('home');
Route::get('/home', 'HomeController@landing')->name('landing');
Route::get('/sendgmail', 'HomeController@sendGmail');

Route::post('/registered','RegisterWorkshopController@store')->name('register_workshop');

Route::middleware('auth')->group(function(){
    Route::prefix('admin')->middleware('admin')->group(function(){

        Route::get('/',function(){

            $user = Auth::user();

            return view('admin.admin', compact('user'));
        })->name('admin');

        Route::resource('news','NewsController')->except([
            'show','destroy'
        ]);
        Route::get('news/recent-news', 'NewsController@recent')->name('news.recent');

        Route::resource('galleries', 'GalleryController')->except([
            'show','destroy'
        ]);

        Route::resource('participants', 'ParticipantController')->except([
            'show','destroy'
        ]);

        Route::resource('adminAccount', 'AdminAccountController')->except([
            'show','destroy'
        ]);

        Route::get('/news/{news}','NewsController@destroy')->name('news.destroy');
        Route::get('/account/{account}','AdminAccountController@destroy')->name('account.destroy');
        Route::resource('registered', 'RegisterWorkshopController')->except([
            'show','destroy','create','store','update'
        ]);

        Route::get('/news/{news}','NewsController@destroy')->name('news.destroy');
        Route::get('/registered/{registered}','RegisterWorkshopController@destroy')->name('registered.destroy');
        Route::put('/registered/bayar/{registered}','RegisterWorkshopController@update')->name('registered.pay');
        Route::put('/news/change-status/{status}','NewsController@changeStatus')->name('news.change');
        Route::get('admin/galleries/{gallery}','GalleryController@destroy')->name('galleries.destroy');
        Route::get('admin/participants/{participant}','ParticipantController@destroy')->name('participants.destroy');
    });
});

resources/views/admin/registered/edit-news.blade.php
@extends('layouts.admin.app')
@section('title','Dashboard | Edit Artikel')

@section('content')

<div class="m-grid m-grid--hor m-grid--root m-page">
    <!-- BEGIN: Header -->


    <!-- begin::Body -->
    <div
      class="m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body"
    >

      <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
          <div class="d-flex align-items-center">
            <div class="mr-auto">
              <h3 class="m-subheader__title ">Edit Artikel</h3>
            </div>
            <div>
              <span
                class="m-subheader__daterange"
                id="m_dashboard_daterangepicker"
              >
                <span class="m-subheader__daterange-label">
                  <span class="m-subheader__daterange-title"></span>
                  <span
                    class="m-subheader__daterange-date m--font-brand"
                  ></span>
                </span>
                <a
                  href="#"
                  class="btn btn-sm btn-brand m-btn m-btn--icon m-btn--icon-only m-btn--custom m-btn--pill"
                >
                  <i class="la la-angle-down"></i>
                </a>
              </span>
            </div>
          </div>
        </div>

        <!-- END: Subheader -->
        <div class="m-content">

            <!--Begin::Section-->
            @if ($errors->any())
                @foreach ($errors->all() as $error)
                <div class="m-alert m-alert--icon alert m-alert--square alert-danger m--margin-bottom-25" role="alert">
                    <div class="m-alert__icon">
                        <i class="la la-exclamation-triangle"></i>
                    </div>
                    <div class="m-alert__text">
                        {{$error}}
                    </div>
                    <div class="m-alert__close">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        </button>
                    </div>
                </div>
                @endforeach
            @endif
            @if (session('warning'))
            <div class="m-alert m-alert--icon alert m-alert--square alert-warning m--margin-bottom-25" role="alert">
                <div class="m-alert__icon">
                    <i class="la la-exclamation-triangle"></i>
                </div>
                <div class="m-alert__text">
                    {{session('warning')}}
                </div>
                <div class="m-alert__close">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    </button>
                </div>
            </div>
            @endif
            @if (session('success'))
            <div class="m-alert m-alert--icon alert m-alert--square alert-success m--margin-bottom-25" role="alert">
                <div class="m-alert__icon">
                    <i class="la la-exclamation-triangle"></i>
                </div>
                <div class="m-alert__text">
                    {{session('success')}}
                </div>
                <div class="m-alert__close">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    </button>
                </div>
            </div>
            @endif
						<div class="row">
                                <div class="col-xl-12">
                                    <div class="m-portlet m-portlet--head-lg">
                                        <div class="m-portlet__head">
                                            <div class="m-portlet__head-caption">
                                                <div class="m-portlet__head-title">
                                                    <span class="m-portlet__head-icon">
                                                        <i class="la la-edit"></i>
                                                    </span>
                                                    <h3 class="m-portlet__head-text">
                                                        Edit Artikel Workshop
                                                    </h3>
                                                </div>
                                            </div>
                                        </div>

                                        <!--begin::Form-->
                                    <form class="m-form m-form--state m-form--label-align-left" action="{{ route('news.update',$news->id) }}" method="POST" enctype="multipart/form-data">
                                            @csrf
                                            @method('PUT')
                                            <div class="m-portlet__body">
                                                <div class="row">
                                                    <div class="col-xl-12">
                                                        <div class="m-form__section">
                                                            <div class="form-group m-form__group row">
                                                                <div class="col-lg-6 m-form__group-sub">
                                                                    <label class="form-control-label">Judul Workshop</label>
                                                                    <input type="text" name="title" value="{{ucfirst($news->title)}}" class="form-control m-input" placeholder="Masukkan Judul">
                                                                    <div class="form-control-feedback">Sorry, that username's taken. Try another?</div>
                                                                    <span class="m-form__help">Please enter your text</span>
                                                                </div>
                                                                 <div class="col-lg-6 m-form__group-sub">
                                                                    <label class="form-control-label">Pengisi Workshop</label>
                                                                    <input type="text" class="form-control" name="author" placeholder="Masukkan Nama" value="{{ucfirst($news->author)}}">
                                                                </div>

                                                            </div>


                                                            <div class="m-form__seperator m-form__seperator--dashed m-form__seperator--space"></div>
                                                            <div class="form-group m-form__group row">

                                                                <div class="col-lg-6 m-form__group-sub">
                                                                    <label class="form-control-label">Waktu Mulai</label>
                                                                    <div class="m-input-icon pull-right">
                                                                        <input type="text" name="tgl_mulai" value="{{$news->tgl_mulai}}" class="form-control" id="m_datetimepicker_3" readonly placeholder="Pilih tanggal dan waktu" />
                                                                        <span class="m-input-icon__icon m-input-icon__icon--right"><span><i class="la la-calendar-check-o"></i></span></span>
                                                                    </div>
                                                                </div>

                                                                <div class="col-lg-6 m-form__group-sub">
                                                                    <label class="form-control-label">Waktu Akhir</label>
                                                                    <div class="m-input-icon pull-right">
                                                                        <input type="text" name="tgl_akhir" value="{{$news->tgl_akhir}}" class="form-control" id="m_datetimepicker_3" readonly placeholder="Pilih tanggal dan waktu" />
                                                                        <span class="m-input-icon__icon m-input-icon__icon--right"><span><i class="la la-calendar-check-o"></i></span></span>
                                                                    </div>
                                                                </div>


                                                            </div>
                                                            <div class="form-group m-form__group row">

                                                                <div class="col-lg-6 m-form__group-sub">
                                                                    <label class="form-control-label">Lokasi Workshop</label>
                                                                    <input type="text" class="form-control" name="location" placeholder="Masukkan Lokasi"   value="{{$news->location}}">
                                                                </div>

                                                                <div class="col-lg-6 m-form__group-sub">
                                                                    <label class="form-control-label">Upload gambar</label>
                                                                    <div class="input-group file-input">
                                                                        <input type="file" class="upload" multiple name="foto">
                                                                        <input type="hidden" name="fotoLama" value="{{$news->foto}}">
                                                                        <input class="form-control" placeholder="No File Selected" type="text">
                                                                        <span class="remove-file"><i class="la la-times-circle"></i></span>
                                                                        <div class="input-group-append">
                                                                            <button type="button" class="btn btn-primary file-name"><i class="la la-file"></i></button>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                            <div class="form-group m-form__group row">
                                                                    <div class="col-sm-12">
                                                                        <label class="col-form-labe">Deskripsi (optional)</label>
                                                                    <textarea name="description" required id="m_summernote_1" class="summernote" cols="30" rows="10">{{$news->description}}</textarea>
                                                                    </div>
                                                                </div>

                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                            <div class="m-portlet__foot m-portlet__foot--fit">
                                                <div class="m-form__actions m-form__actions--solid">
                                                    <div class="row">
                                                        <div class="col-xl-12 m--align-right">
                                                            <button type="submit" class="btn btn-primary btn-sm m-btn--pill m-btn--air m-btn--wide">Update</button>
                                                            <a href="{{route('news.index')}}" class="btn btn-secondary btn-sm m-btn--wide m-btn--pill m--margin-left-5">Cancel</a>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </form>

                                        <!--end::Form-->
                                    </div>

                                    <!--End::Portlet-->
                                </div>
                            </div>

                            <!--End::Section-->
                      </div>
                      </div>
                      </div>
                      </div>

  <!-- end:: Page -->

  <!-- begin::Scroll Top -->
  <div id="m_scroll_top" class="m-scroll-top">
    <i class="la la-arrow-up"></i>
  </div>

  <!-- end::Scroll Top -->
@endsection

resources/views/admin/registered/index.blade.php
@extends('layouts.admin.app')
@section('title','Dashboard | Registered Workshop')

@section('content')

<div class="m-grid m-grid--hor m-grid--root m-page">
    <!-- BEGIN: Header -->


    <!-- begin::Body -->
    <div
      class="m-grid__item m-grid__item--fluid m-grid m-grid--ver-desktop m-grid--desktop m-body"
    >

      <div class="m-grid__item m-grid__item--fluid m-wrapper">
        <!-- BEGIN: Subheader -->
        <div class="m-subheader ">
            <div class="d-flex align-items-center">
                <div class="mr-auto">
                    <h3 class="m-subheader__title m-subheader__title--separator">Register Workshop</h3>
                    <ul class="m-subheader__breadcrumbs m-nav m-nav--inline">
                        <li class="m-nav__item m-nav__item--home">
                            <a href="{{ route('admin') }}" class="m-nav__link m-nav__link--icon">
                                <i class="m-nav__link-icon la la-home"></i>
                            </a>
                        </li>
                        <li class="m-nav__separator">-</li>
                        <li class="m-nav__item">
                            <a href="{{ route('registered.index') }}" class="m-nav__link ">
                                <span class="m-nav__link-text">Register Workshop</span>
                            </a>
                        </li>


                    </ul>
                </div>
            </div>
        </div>

        <!-- END: Subheader -->
        <div class="m-content">
                @if ($errors->any())
                @foreach ($errors->all() as $error)
                <div class="m-alert m-alert--icon alert m-alert--square alert-danger m--margin-bottom-25" role="alert">
                    <div class="m-alert__icon">
                        <i class="la la-exclamation-triangle"></i>
                    </div>
                    <div class="m-alert__text">
                        {{$error}}
                    </div>
                    <div class="m-alert__close">
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        </button>
                    </div>
                </div>
                @endforeach
            @endif
            @if (session('warning'))
            <div class="m-alert m-alert--icon alert m-alert--square alert-warning m--margin-bottom-25" role="alert">
                <div class="m-alert__icon">
                    <i class="la la-exclamation-triangle"></i>
                </div>
                <div class="m-alert__text">
                    {{session('warning')}}
                </div>
                <div class="m-alert__close">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    </button>
                </div>
            </div>
            @endif
            @if (session('message'))
            <div class="m-alert m-alert--icon alert m-alert--square alert-success m--margin-bottom-25" role="alert">
                <div class="m-alert__icon">
                    <i class="la la-check-circle-o"></i>
                </div>
                <div class="m-alert__text">
                    {{session('message')}}
                </div>
                <div class="m-alert__close">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    </button>
                </div>
            </div>
            @endif
			<div class="row">
                <div class="col-xl-12">
                    <!--Begin::Portlet-->
                    <div class="m-portlet m-portlet--head-lg">
                        <div class="m-portlet__body no-pedding">
                            <div class="m-portlet__head">
                                <div class="m-portlet__head-caption">
                                    <div class="m-portlet__head-title">
                                        <span class="m-portlet__head-icon">
                                            <i class="la la-table"></i>
                                        </span>
                                        <h3 class="m-portlet__head-text">
                                            Table Register Workshop
                                        </h3>
                                    </div>
                                </div>
                                <div class="m-portlet__head-tools">

                            </div>
                            </div>
                        </div>

                        <div class="table-responsive" style="padding-top: 50px;">
                            <table class="table align-items-center table-flush" id="table-id">
                                <thead class="thead-light">
                                    <tr>
                                    <th scope="col">No</th>
                                    <th scope="col">Name</th>
                                    <th scope="col">Workshop</th>
                                    <th scope="col">Email</th>
                                    <th scope="col">No Telp</th>
                                    <th scope="col">Ukuran Baju</th>
                                    <th scope="col">Status</th>
                                    <th scope="col">Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @php
                                        $no = 1;
                                    @endphp
                                    @foreach ($data as $g)
                                    <tr>
                                        <th>{{$no++}}</th>
                                        <td>{{ $g->nama }}</td>
                                        <td>{{ ucfirst($g->news->title) }}</td>
                                        <td>{{ $g->email }}</td>
                                        <td>{{ $g->number_telp }}</td>
                                        <td>{{ strtoupper($g->size_chart) }}</td>
                                        <td><div class="section__status">
                                        @if ( $g->status == '0')
                                            <span class="m-badge m-badge--warning text-white m-badge--wide">Belum bayar</span>
                                        @else
                                            <span class="m-badge m-badge--success m-badge--wide">Bayar</span>
                                        @endif
                                        </div></td>
                                        <td>
                                            <div class="section__action">
												<div class="list__section__action">
                                                </div>
                                                <div class="m-dropdown m-dropdown--inline m-dropdown--arrow m-dropdown--align-right m-dropdown--align-push m-dropdown--up" m-dropdown-toggle="click" aria-expanded="true">
														<a href="#" data-toggle="kt-tooltip" data-placement="bottom" title="Action" data-skin="brand" class="btn m-btn btn-outline-metal m-btn--icon btn-sm m-btn--icon-only m-btn--square  m-dropdown__toggle">
															<i class="la la-ellipsis-h"></i>
														</a>
														<div class="m-dropdown__wrapper" style="z-index: 101;">
														<div class="m-dropdown__inner">
															<div class="m-dropdown__body">
																<div class="m-dropdown__content">
																	<ul class="m-nav">
																		<li class="m-nav__section m-nav__section--first">
																			<span class="m-nav__section-text">Quick Actions</span>
																		</li>
																		<li class="m-nav__separator m-nav__separator--fit"></li>
																		<li class="m-nav__item">
                                                                            <form action="{{route('registered.pay',$g->id)}}" method="POST">
                                                                            @csrf
                                                                            @method('put')
																			@if ($g->status == '1')
                                                                            <h5>Sudah dibayar</h5>
                                                                                @else
                                                                                <button type="submit" class="btn m-btn btn-outline-danger btn-sm" >
                                                                                        <i class="m-nav__link-icon flat la la-pencil-square"></i>
                                                                                        <span class="m-nav__link-text">Bayar</span>
                                                                                    </button>

                                                                            @endif
                                                                            </form>
																		</li>
																	</ul>
																	<!--Move Here-->
																</div>
															</div>
														</div>
														<span class="m-dropdown__arrow m-dropdown__arrow--right"></span>
													</div>
                                                    </div>
                                                    <a href="{{route('registered.destroy',$g->id)}}" data-toggle="kt-tooltip" data-placement="bottom" title="Hapus" data-skin="brand" class="btn-delete btn m-btn btn-outline-danger btn-sm  m-btn--icon m-btn--pill icon-only">
                                                            <span>
                                                                <i class="la la-trash"></i>
                                                            <span>Delete</span>
                                                            </span>
                                                        </a>
                                            </div>


                                        </td>
                                    </tr>
                                    @endforeach
                                    {{ $data->render() }}
                                </tbody>
                            </table>
                        </div>

                    </div>
                </div>
			</div>
        </div>
    </div>
</div>
</div>

  <!-- end:: Page -->

  <!-- begin::Scroll Top -->
  <div id="m_scroll_top" class="m-scroll-top">
    <i class="la la-arrow-up"></i>
  </div>

  <!-- end::Scroll Top -->
@endsection

@section('admin-js')

  <script>
    $(document).ready(function(){



        $(function () {
            $('[data-toggle="kt-tooltip"]').tooltip();
        })

        $('.btn-delete').click(function(e){
            e.preventDefault();
            var link_project = $(this).attr('href');
            swal({
                title: 'Are you sure?',
                type:'warning',
                showCancelButton:true,
                cancelButtonColor:'#d33',
                confirmButtonColoro:'#3085d6'
            }).then((result)=>{
                if(result.value){
                    window.location.href= link_project;
                    console.log('delete button clicked');
                }
            });
        });

    });

  </script>

@endsection